# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_create',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date_happen',
            new_name='event_date',
        ),
    ]
